[build]
  # Directory to change to before starting a build
  base = "."

  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"

  # Default build command
  command = "CI=false npm run build"

[build.environment]
  # Treat warnings as warnings, not errors
  CI = "false"

  # Node version
  NODE_VERSION = "18"

  # API Configuration - Updated for latest backend
  REACT_APP_API_URL = "https://backend-newone.vercel.app/api"

  # Application Configuration
  REACT_APP_NAME = "PITCS - Champions HR Services"
  REACT_APP_VERSION = "1.0.0"

  # Contact Information
  REACT_APP_CONTACT_EMAIL = "jobs@championshservices.com"
  REACT_APP_CONTACT_PHONE = "+91-9632492563"

  # Google Form URL for job applications
  REACT_APP_GOOGLE_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLScRvVyo6og6ntYbH9Y12OaxBD1lCZcq_iv7TFRNpW3BbTralg/viewform?usp=sf_link"

  # Development/Production Mode
  REACT_APP_ENV = "production"

  # Enable/Disable Features
  REACT_APP_ENABLE_RESUME_UPLOAD = "true"
  REACT_APP_ENABLE_JOB_ALERTS = "true"
  REACT_APP_ENABLE_ANALYTICS = "false"

  # File Upload Configuration
  REACT_APP_MAX_FILE_SIZE = "5242880"
  REACT_APP_ALLOWED_FILE_TYPES = ".pdf,.doc,.docx"

  # Social Media Links
  REACT_APP_FACEBOOK_URL = "https://facebook.com/championshservices"
  REACT_APP_LINKEDIN_URL = "https://linkedin.com/company/championshservices"
  REACT_APP_TWITTER_URL = "https://twitter.com/championshservices"
  REACT_APP_YOUTUBE_URL = "https://youtube.com/@championshservices"
  REACT_APP_INSTAGRAM_URL = "https://instagram.com/championshservices"

  # Company Information
  REACT_APP_COMPANY_NAME = "Champions HR Services"
  REACT_APP_COMPANY_ADDRESS = "Bangalore, India"
  REACT_APP_COMPANY_WEBSITE = "https://championshservices.com"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
